sudo: false
language: c

matrix:
  include:

    - name: "Windows/GCC+GMake/Shared x86 (try multilib)"
      os: windows
      compiler: gcc
      env:
        - BUILD_DIR=win/build
        - CFGOPT="--enable-threads --disable-64bit"
      before_install:
        - choco install make
        # install multilib mingw:
        - |
          wget -q -O /tmp/install.7z 'https://sourceforge.net/projects/mingw-w64/files/Multilib%20Toolchains%28Targetting%20Win32%20and%20Win64%29/ray_linn/gcc-8.x-with-ada/x86_64-w64-mingw32-8.3.0-crt-6.0.0-multilib.7z/download'
          mgwpath=/c/ProgramData/chocolatey/lib/mingw/tools/install
          7z x /tmp/install.7z -r -aoa -o$mgwpath
          $mgwpath/mingw64/setup.bat
          export PATH=$mgwpath/mingw64/bin:$PATH
        - $CC --version
        #- $CC -m32 -dM -E - < /dev/null
      install:
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        # the options belong after command (ar cr --target=pe-i386 ...), but we not need it in CI:
        #- CFLAGS=-m32 LDFLAGS=-m32 AR='ar --target=pe-i386' RC='windres --target=pe-i386' ../configure --enable-threads --disable-64bit
        - CFLAGS=-m32 LDFLAGS=-m32 RC='windres --target=pe-i386' ../configure --enable-threads --disable-64bit
      script:
        - make all
        - make tcltest
        - |
          echo 'dict for {k v} [array get tcl_platform] {puts [format %4s%-20s%s "" ${k}: $v]}' | ./tcltest.exe
        #- make test TESTFLAGS="-tmpdir $(cd $TEMP && pwd -W || pwd -P)"
        #- ./tcltest
        - make test

    - name: "Windows/GCC+GMake/Shared x86 (upgrade toolchain to x86)"
      os: windows
      compiler: gcc
      env:
        - BUILD_DIR=win/build
        - CFGOPT="--enable-threads --disable-64bit"
      before_install:
        - choco install make
        - choco upgrade mingw --x86 --force
        - refreshenv
        - $CC --version
        - export PATH=/c/tools/mingw32/bin:$PATH
        #- $CC -m32 -dM -E - < /dev/null
      install:
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        # x86 with multilib mingw (e. g. x86_64-w64-mingw32-8.3.0-crt-6.0.0-multilib.7z)
        #- CFLAGS=-m32 LDFLAGS=-m32 AR='ar' RC='windres --target=pe-i386' ../configure --enable-threads --disable-64bit
        - ../configure --enable-threads --disable-64bit
      script:
        - make all
        - make tcltest
        - |
          echo 'dict for {k v} [array get tcl_platform] {puts [format %4s%-20s%s "" ${k}: $v]}' | ./tcltest.exe
        #- make test TESTFLAGS="-tmpdir $(cd $TEMP && pwd -W || pwd -P)"
        #- ./tcltest
        - make test

    - name: "Windows/GCC+GMake/Shared x64"
      os: windows
      compiler: gcc
      env:
        - BUILD_DIR=win/build
        - CFGOPT="--enable-threads --enable-64bit"
      before_install:
        - choco install make
        - echo $(make --version)
        - (gcc -m64 -dM -E - < /dev/null) | grep MINGW
      script:
        - make all
        - |
          echo 'dict for {k v} [array get tcl_platform] {puts [format %4s%-20s%s "" ${k}: $v]}' | ./tclsh86.exe
        - make tcltest
        - |
          echo 'dict for {k v} [array get tcl_platform] {puts [format %4s%-20s%s "" ${k}: $v]}' | ./tcltest.exe
        # windows tests should work in temporary folder (permissions related on some relative path, e. g. winFCmd, etc):
        - ./tcltest.cmd
        #- make test

before_install:
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
install:
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - ../configure ${CFGOPT} --prefix=$HOME
  # for debugging only
  #- cat Makefile

before_script:
  - export ERROR_ON_FAILURES=1

script:
  - make all
  - make tcltest
  - make test
