sudo: false
language: c

matrix:
  include:
# Test on Windows with GCC native (make)
    - name: "Windows/GCC+GMake/Shared x86"
      os: windows
      compiler: gcc
      env:
        - BUILD_DIR=win/build
        - CFGOPT="--enable-threads --disable-64bit"
      before_install:
        - choco install make
        - choco install mingw --x86 --force
        - gcc --version
        - (gcc -m32 -dM -E - < /dev/null) | grep MINGW
      script:
        - echo $(pwd)
        - make all
        - make tcltest
        - make test TESTFLAGS="-tmpdir $(cd $TEMP && pwd -W || pwd -P)"

# Test on Windows with GCC native (make)
    - name: "Windows/GCC+GMake/Shared x64"
      os: windows
      compiler: gcc
      env:
        - BUILD_DIR=win/build
        - CFGOPT="--enable-threads --enable-64bit"
      before_install:
        - choco install make
        - echo $(make --version)
        - (gcc -m64 -dM -E - < /dev/null) | grep MINGW
      script:
        - echo $(pwd)
        - make all
        - make tcltest
        - make test TESTFLAGS="-tmpdir $(cd $TEMP && pwd -W || pwd -P)"

before_install:
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
install:
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - ../configure ${CFGOPT} --prefix=$HOME
  # for debugging only
  #- cat Makefile

before_script:
  - export ERROR_ON_FAILURES=1

script:
  - make all
  - make tcltest
  - make test
