sudo: false
language: c

matrix:
  include:

# Test on Windows with MSVC native
    - name: "Windows/MSVC/Shared"
      os: windows
      compiler: cl
      env: &vcenv
        - BUILD_DIR=win
        - VCDIR="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Auxiliary/Build"
      install: &vcinst
        - PATH="$PATH:$VCDIR"
        - cd ${BUILD_DIR}
      script:
        - cmd.exe /C 'vcvarsall.bat x64 && nmake OPTS=threads -f makefile.vc all tcltest'
        - cmd.exe /C 'vcvarsall.bat x64 && nmake OPTS=threads -f makefile.vc test TESTFLAGS="-file *io.test -verbose tpm"'
    - name: "Windows/MSVC/Static"
      os: windows
      compiler: cl
      env: *vcenv
      install: *vcinst
      script:
        - cmd.exe /C 'vcvarsall.bat x64 && nmake OPTS=static,msvcrt,threads -f makefile.vc all tcltest'
        - cmd.exe /C 'vcvarsall.bat x64 && nmake OPTS=static,msvcrt,threads -f makefile.vc test TESTFLAGS="-file *io.test -verbose tpm"'
    - name: "Windows/MSVC/Debug"
      os: windows
      compiler: cl
      env: *vcenv
      install: *vcinst
      script:
        - cmd.exe /C 'vcvarsall.bat x64 && nmake OPTS=symbols,msvcrt,threads -f makefile.vc all tcltest'
        - cmd.exe /C 'vcvarsall.bat x64 && nmake OPTS=symbols,msvcrt,threads -f makefile.vc test TESTFLAGS="-file *io.test -verbose tpm"'

    - name: "Windows/GCC/Shared x86 (multilib, mingw-8.3)"
      os: windows
      env:
        - BUILD_DIR=win/bld32
        - CFGOPT="--enable-threads --disable-64bit"
        # (todo) the option for AR belong after command (ar cr --target=pe-i386 ...), but we not need it in CI at the moment
        - CFLAGS=-m32 LDFLAGS=-m32 RC="windres --target=pe-i386"
      before_install: &mgwmltlibinst
        - choco install make
        # install multilib mingw:
        - |
          wget -q -O /tmp/install.7z 'https://sourceforge.net/projects/mingw-w64/files/Multilib%20Toolchains%28Targetting%20Win32%20and%20Win64%29/ray_linn/gcc-8.x-with-ada/x86_64-w64-mingw32-8.3.0-crt-6.0.0-multilib.7z/download'
          mgwpath=/c/ProgramData/chocolatey/lib/mingw/tools/install
          7z x /tmp/install.7z -r -aoa -o$mgwpath
          # atm don't need to setup it (add to path is enough):
          # echo '' | $mgwpath/mingw64/setup.bat
          export PATH=$mgwpath/mingw64/bin:$PATH
        - gcc --version
      install: &mgwinst
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - ../configure ${CFGOPT} || (cat config.log && exit 1)
      script: &mgwscript
        #
        - make all tcltest
        - |
          echo 'dict for {k v} [array get tcl_platform] {puts [format %4s%-20s%s "" ${k}: $v]}' | ./tcltest.exe

        # (todo) windows tests should work in temporary folder (permissions related on some relative path, e. g. winFCmd, etc):
        # make test TESTFLAGS='-tmpdir 1'
        - ./tcltest.sh -file *io.test -verbose tpm

    - name: "Windows/GCC/Shared x64 (multilib, mingw-8.3)"
      os: windows
      env:
        - BUILD_DIR=win/bld64
        - CFGOPT="--enable-threads --enable-64bit"
        # (todo) the option for AR belong after command (ar cr --target=pe-x86-64 ...), but we not need it in CI at the moment
        - CFLAGS=-m64 LDFLAGS=-m64 RC='windres --target=pe-x86-64'
      before_install: *mgwmltlibinst
      install: *mgwinst
      script: *mgwscript

    - name: "Windows/GCC/Shared x64"
      os: windows
      compiler: gcc
      env:
        - BUILD_DIR=win/build
        - CFGOPT="--enable-threads --enable-64bit"
      before_install:
        - choco install make
        #- (gcc -m64 -dM -E - < /dev/null) | grep MINGW
      install: *mgwinst
      script: *mgwscript

install:
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - ../configure ${CFGOPT} --prefix=$HOME
before_script:
  - export ERROR_ON_FAILURES=1
script:
  - make all tcltest
  - make test
