sudo: false
language: c

matrix:
  include:
# Test on Windows with GCC native (make)
    - name: "Windows/GCC+GMake/Shared x86"
      os: windows
      compiler: gcc
      env:
        - BUILD_DIR=win/build
        - CFGOPT="--enable-threads --disable-64bit"
      before_install:
        - choco install make
        - echo $(make --version)
      script:
        - echo $(pwd)
        - make all
        - make --debug=verbose tcltest
        - make test

# Test on Windows with GCC native (make)
    - name: "Windows/GCC+GMake/Shared x64"
      os: windows
      compiler: gcc
      env:
        - BUILD_DIR=win/build
        - CFGOPT="--enable-threads --enable-64bit"
      before_install:
        - choco install make
        - echo $(make --version)
      script:
        - echo $(pwd)
        - make all
        - make --debug=verbose tcltest
        - make test

before_install:
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
install:
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - ../configure ${CFGOPT} --prefix=$HOME
  # for debugging only
  - cat Makefile

before_script:
  - export ERROR_ON_FAILURES=1

script:
  - make all
  - make tcltest
  - make test
