dist: trusty
sudo: false
language: c
matrix:
  include:
# Test with mingw 32 bit
    - os: linux
      compiler: i686-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - gcc-mingw-w64      
            - gcc-multilib
            - wine-devel
      env:
        - BUILD_DIR=win
        - CFGOPT=--host=i686-w64-mingw32

# Test with mingw 64 bit
    - os: linux
      compiler: x86_64-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
            - gcc-mingw-w64
            - wine-devel
      env:
        - BUILD_DIR=win
        - CFGOPT=--host=x86_64-w64-mingw32 --enable-64bit

before_install:
  - eval "${MATRIX_EVAL}"
  - export ERROR_ON_FAILURES=1
  - cd ${BUILD_DIR}
install:
  - test -n "$NO_DIRECT_CONFIGURE" || ./configure ${CFGOPT}
script:
  - make
  - make test-tcl
