name: Linux Build and Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        working-directory: unix
        run: |
          mkdir "${HOME}/install dir"
          ./configure ${CFGOPT} "--prefix=$HOME/install dir" || (cat config.log && exit 1)
      - name: Build
        working-directory: unix
        run: |
          make all
      - name: Build Test Harness
        working-directory: unix
        run: |
          make tcltest
      - name: Run Tests
        working-directory: unix
        run: |
          make test
      - name: Test-Drive Installation
        working-directory: unix
        run: |
          make install
      - name: Create Distribution Package
        working-directory: unix
        run: |
          make dist
      - name: Convert Documentation to HTML
        working-directory: unix
        run: |
          make html-tcl
