name: Windows Build and Test
on: [push]
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: win
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: |
          nmake -f makefile.vc all
      - name: Build Test Harness
        run: |
          nmake -f makefile.vc tcltest
      - name: Run Tests
        run: |
          nmake -f makefile.vc test
